name: "Hello Actions"
description: "Greetings haha"
author: "eduardo-aop"

inputs:
	MY_FIRST_ACTION:
		description: "Who to greet"
		required: true
		default: "World"

runs:
	using: "docker"
	image: "Dockerfile"

branding:
	icon: "mic"
	color: "purple"
